# Generated by Django 4.2 on 2024-01-25 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='snippet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.snippet'),
        ),
    ]
